# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_A1
      - joint_A2
      - joint_A3
      - joint_B1
      - joint_B2
      - joint_B3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity